travis:
  secure:
    BINSTAR_TOKEN: 1vzc+eJ62Btv4ebpfWVF+3UvN/ueyRP0/2FQ9riJVN22qJhSlPsDJyTSRPu5ysgxKVvWRh6/V2VsWvYQmxgp2aCtpquiWkFYGeWSlNWj9Q3RQ8a09ylnhjXoozavRaB57gJx3506nkZ1VaT6OHb2cC7gVeBLcan8manFFZxNoo8bQ+znHpqnqGQGMA0Etnkpf0tcs+X36K31rrvzKDFPTBcg4mX0wcrIEjhgLPv7Z7rMRAsU/3EoNJ+NboyrsjLLI68lIr1YRiG3Dt6AaWQBxZ83WO06cCurNiF+g5t3TIUClKnnGrPsM+9PHzxd3kUNg4573T8AUkZ5iwtLt8pZ/SsCOt0dqAryyj8wUZWpalw6G0E71wPRtDZLdPbHZ6J4O7B3DAYxdE48fPH6IaqBC+WmqkAF0tUCVpRadGVtopOHVAEyXGeMaQ0cLTOOXvqIzMBMonzTO7Uyk1mrWZle5vUoCglmYVLL2Ty8pcUXjMc3ZhI4e2wvuaOQsPbMqZmePDTzxBZk8QJ6mc1IunYlYtpx82rXriofXjWWmW95ADApKFlMUuNjGWslbWUj+G2l1HqBhkiEcwuUl6rtrBh18XFBAGXramhgw1HeiZ28Tcxr3yGkezFeQqoKTe5WLV3ew3A+cx8TILOFSNdJGGp3O44D1x6QG6a8RCZvG+j+N9E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
